### ISSUE TITLE
Setup Admin accountablity

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-decidim_awesome#2]
**Global requirement:**

As a platform-admin I would like to be able to get an excel list with information about the assembly- and process-admins at any given date and time. The list should include name, e-mail address and according assembly / process (must). Additionally the belonging filter criteria (scope type, assembly type) (nice to have).

**Tasks:**

- [x] Create a new section "Admin accountability" in Decidim Participants submenu
- [x] Create basic Controller/permissions class with a placeholder for further development (see #3)
- [x] Add basic tests (also system tests)

Initial mockup: This step only requires to show the menu, handle the permissions for restricting access to admins and show a view with a placeholder
![imatge](https://user-images.githubusercontent.com/40388743/212127720-f76dc3e6-daef-433e-83ba-60e5a6bbdf3c.png)

Mockup for the finished product (when all issues completed):
![imatge](https://user-images.githubusercontent.com/40388743/212125116-85d8c521-bf22-41d6-9671-f43013be1dc5.png)

**Update**

- [x] Add a new conf var in `lib/decidim/decidim_awesome/awesome.rb` named `admin_accountability`, expected `true`, `false` values.
- [x] If true, it behaves as decribed. If false, this feature should be disabled. No menu present
