### ISSUE TITLE
View and controllers

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-decidim_awesome#3]
Depends on #2 

This task must make use of the `Decidim::ActionLog` to list all the admins that have been active in a given period of time. Initially it must not be filtered so it must show a list of all the users that have been given the role of admin at any time.

**Tasks:**
- [x] Improve controller defined in #2, filter events in `ActionLog` and show the list in the index view. Note that we need to filter for `resource_type` == `Decidim::ParticipatoryProcessUserRole` and show all the roles.
- [x] Take into account that some information must have retrieved from the linked resource (the user), such as the email. And this might be deleted or empty, show a `(missing information)` text in this case.
- [x] Paginate results
- [x] Create tests/system tests

Mockup: 
![imatge](https://user-images.githubusercontent.com/40388743/212127254-a9f0c5ca-3b8e-4c5e-b984-3a0d422b0c34.png)

Development notes:

This is and `ActionLog` entry for a user that has been given permissions in a participatory space:

```ruby
#<Decidim::ActionLog:0x000055cd3b25f310
 id: 1133,
 decidim_organization_id: 1,
 decidim_user_id: 1,
 decidim_component_id: nil,
 resource_type: "Decidim::ParticipatoryProcessUserRole",
 resource_id: 9,
 participatory_space_type: "Decidim::ParticipatoryProcess",
 participatory_space_id: 2,
 action: "create",
 extra:
  {"user"=>
    {"ip"=>"127.0.0.1", "name"=>"Mr. Dede Christiansen", "nickname"=>"admin"},
   "resource"=>{"title"=>"Reuben Boehm"},
   "component"=>{},
   "participatory_space"=>
    {"title"=>
      {"ca"=>"Ratione quam voluptas minus dolorum.",
       "cs"=>"Voluptatibus voluptas eum dolores error.",
       "de"=>"Eius et sit possimus alias.",
       "en"=>"Molestiae asperiores ullam magni sit.",
       "es"=>"Voluptas ab consequatur quam eos.",
       "eu"=>"Commodi voluptas quibusdam rem quia.",
       "fi"=>"Nihil laboriosam id a facere.",
       "fr"=>"Deleniti nihil laboriosam quia aut.",
       "it"=>"Possimus veniam vitae quo amet.",
       "ja"=>"フランス語きょうはんしゃ機嫌飽くまでも渦巻き。",
       "nl"=>"Enim dicta omnis dolor est.",
       "pl"=>"Qui est numquam quaerat in.",
       "pt"=>"Ut est cumque numquam aut.",
       "machine_translations"=>{"ro"=>"Minus iste sunt ut eum."}},
     "manifest_name"=>"participatory_processes"}},
 created_at: Thu, 12 Jan 2023 15:25:41 UTC +00:00,
 updated_at: Thu, 12 Jan 2023 15:25:41 UTC +00:00,
 version_id: 1900,
 visibility: "admin-only",
 decidim_scope_id: nil,
 decidim_area_id: nil>
```

This is and `ActionLog` entry for a user with permissions just removed from a participatory space:

```ruby
#<Decidim::ActionLog:0x000055cd3afcef10
 id: 1134,
 decidim_organization_id: 1,
 decidim_user_id: 1,
 decidim_component_id: nil,
 resource_type: "Decidim::ParticipatoryProcessUserRole",
 resource_id: 9,
 participatory_space_type: "Decidim::ParticipatoryProcess",
 participatory_space_id: 2,
 action: "delete",
 extra:
  {"user"=>
    {"ip"=>"127.0.0.1", "name"=>"Mr. Dede Christiansen", "nickname"=>"admin"},
   "resource"=>{"title"=>"Reuben Boehm"},
   "component"=>{},
   "participatory_space"=>
    {"title"=>
      {"ca"=>"Ratione quam voluptas minus dolorum.",
       "cs"=>"Voluptatibus voluptas eum dolores error.",
       "de"=>"Eius et sit possimus alias.",
       "en"=>"Molestiae asperiores ullam magni sit.",
       "es"=>"Voluptas ab consequatur quam eos.",
       "eu"=>"Commodi voluptas quibusdam rem quia.",
       "fi"=>"Nihil laboriosam id a facere.",
       "fr"=>"Deleniti nihil laboriosam quia aut.",
       "it"=>"Possimus veniam vitae quo amet.",
       "ja"=>"フランス語きょうはんしゃ機嫌飽くまでも渦巻き。",
       "nl"=>"Enim dicta omnis dolor est.",
       "pl"=>"Qui est numquam quaerat in.",
       "pt"=>"Ut est cumque numquam aut.",
       "machine_translations"=>{"ro"=>"Minus iste sunt ut eum."}},
     "manifest_name"=>"participatory_processes"}},
 created_at: Thu, 12 Jan 2023 15:32:19 UTC +00:00,
 updated_at: Thu, 12 Jan 2023 15:32:19 UTC +00:00,
 version_id: 1901,
 visibility: "admin-only",
 decidim_scope_id: nil,
 decidim_area_id: nil>
```
