### ISSUE TITLE
Search and filtering

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-decidim_awesome#4]
Depends on #3

In this step we will add filtering capabilities to the controller developed in #3 

**Tasks**
- [x] Filter by name or nickname or name of the participatory space in the generic text box
- [x] Filter by role type in the dropdown menu
- [x] FIlter by type of participatory spaces (participatory process, assembly, etc) in the dropdown menu
- [x] Filter by date using its dedicated fields
- [x] Tests

Mockup:
![imatge](https://user-images.githubusercontent.com/40388743/212127022-bd77d545-d29f-44f2-b689-30776e21909e.png)
